version: '3.3'
services:
  discovery-server:
    image: jovaniac/eureka-discovery:0.0.1-snapshot
    ports:
      - 8761:8761
  postgres-service:
    build: servicesData/postgresdb/
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - ./blockstorage/postgres:/var/lib/postgresql/data
  api-seguros-guadalupe:
    image: jovaniac/api-seguros-guadalupe:0.0.1-snapshot
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-service:5432/seguros_guadalupe
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    ports:
      - "8081:8081"
    depends_on:
      - postgres-service
  api-seguros-guadalupe-administracion:
    image: jovaniac/api-seguros-guadalupe-administracion:0.0.1-snapshot
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-service:5432/seguros_guadalupe_administracion
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    ports:
      - "8082:8082"
    depends_on:
      - postgres-service