server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true
 
  #Por defecto, Eureka usa el latido del cliente para determinar si un cliente está activo. 
  #A menos que se especifique lo contrario, Discovery Client no propaga el estado actual de comprobación de estado 
  #de la aplicación, según Spring Boot Actuator. En consecuencia, después de un registro exitoso, E
  #ureka siempre anuncia que la aplicación está en estado 'ARRIBA'. Este comportamiento puede alterarse 
  #habilitando las comprobaciones de estado de Eureka, lo que resulta en la propagación del estado de la a
  #plicación a Eureka. Como consecuencia, cualquier otra aplicación no envía tráfico a las aplicaciones en estados que no sean 'ARRIBA'. El siguiente ejemplo muestra cómo habilitar las comprobaciones de estado para el cliente: