version: '3.3'
services:
  postgres-service:
    build: servicesData/postgresdb/
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - ./blockstorage/postgres:/var/lib/postgresql/data
  api-seguros-guadalupe:
    image: jovaniac/api-seguros-guadalupe-http:0.0.1-snapshot
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-service:5432/seguros_guadalupe
    ports:
      - "8081:8081"
    depends_on:
      - postgres-service
  api-seguros-guadalupe-adm:
    image: jovaniac/api-seguros-guadalupe-administracion-http:0.0.1-snapshot
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-service:5432/seguros_guadalupe_administracion
    ports:
      - "8082:8082"
    depends_on:
      - postgres-service